# Generated by Django 3.1.5 on 2021-05-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0002_auto_20210509_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='auth_user_id',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
