# Generated by Django 3.1.5 on 2021-05-03 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0002_auto_20210503_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantuser',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='merchantuser',
            name='name',
        ),
    ]
