# Generated by Django 3.1.5 on 2021-05-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0003_stock_auth_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockhistory',
            name='auth_user_id',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
