# Generated by Django 3.1.5 on 2021-05-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0004_stockhistory_auth_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'Admin'), ('2', 'Staff'), ('3', 'Merchant'), ('4', 'Customer')], default=1, max_length=255),
        ),
    ]
