# Generated by Django 3.1.5 on 2021-05-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0005_auto_20210516_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='gst_details',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
