# Generated by Django 3.1.5 on 2021-05-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0007_auto_20210517_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='profile_pic',
            field=models.FileField(default='media/profile.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='profile_pic',
            field=models.FileField(default='media/profile.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='merchantuser',
            name='profile_pic',
            field=models.FileField(default='media/profile.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='profile_pic',
            field=models.FileField(default='media/profile.png', upload_to=''),
        ),
    ]
