# Generated by Django 3.1.5 on 2021-06-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0008_auto_20210517_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='sub_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='stock',
            table='stock',
        ),
    ]
